### ISSUE TITLE
bugs todo 07.08.

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/TvT_Rattenfalle.Tanoa#20]
- [x] random civs verteilen mit 30% presence und 
- [x] eigener funktion zum ausrüsten (momentan scriptfehler)
- [ ] wasser spawn prüfen (boot auf land?)
- [x] NVG varianten prüfen (blufor bessere?)
- [x] markerintervall abschalten
- [x] zivsichtungen auf sichtungslogik intervall umstellen
